apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullName}}
  labels:
    app: {{ .Values.selectorLabel }}
spec:
  ports:
    - port: {{ .Values.service.native }}
      protocol: TCP
      name: native
    - port: {{ .Values.service.http }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.selectorLabel }}